-----
kind: ReplicationController
apiVersion: v1
metadata:
    name: OCSClustergreen
    labels:
        app: OCSClustergreen
spec:
    replicas: 1
    selector:
        app: OCSClustergreen
    template:
        metadata:
            labels:
                app: OCSClustergreen
        spec:
            containers:
                - name: OCSClustergreen
                  image: ltapfuma/iac-bluegreen
                  ports:
                      - name: http-server
                        containerPort: 80

